### ISSUE TITLE
Do blocks mysteriously flagged 

### ISSUE THREAD

**Issue by BigMcLargeHuge** [migeorge/erb-helper#8]
Hello,

I'm finding that the erb helper is mysteriously flagging the first line of several do blocks in my code.

For example, the first line of this block is flagged with the error `unexpected end-of-input, expecting ')'`

```
<%= link_to company_issues_path(@company), no_turbolink: true do %>
    <% if @company.issues.where(resolved: false).count == 0 %>
        <span id="warn">!</span>
    <% else %>
        <span id="warn" class="warning">!</span>
    <% end %>
    <span class="label"><%= @company.issues.where(resolved: false).count %> Unresolved</span>
<% end %>
```

Another example with error `unexpected ')'`:

```
<%= link_to company_path(@company.id), class: "link dashboard", data: {no_turbolink: true}, title: "Dashboard" do %>
    <span class="icon glyphicon glyphicon-dashboard"></span>
    <span class="label">Dashboard</span>
<% end %>
```

It's entirely possible that I might not be using the best syntax here so if there's a better way to write it feel free to make a suggestion.

**Comment by migeorge** [comment]
Hi,

erb-helper actually just helps you out by assigning a few keyboard shortcuts, so it doesn't actually produce any errors or look at the syntax of your code for that matter. It sounds like your linter is picking up some invalid ruby.

Using your first code block above I'd suggest wrapping the arguments to your link_to in parens like this:

```
<%= link_to(company_issues_path(@company), no_turbolink: true) do %>
    <% if @company.issues.where(resolved: false).count == 0 %>
        <span id="warn">!</span>
    <% else %>
        <span id="warn" class="warning">!</span>
    <% end %>
    <span class="label"><%= @company.issues.where(resolved: false).count %> Unresolved</span>
<% end %>
```

This will ensure that Ruby is interpreting your block as part of the link_to instead of the last argument.

Also, are you disabling turbolinks manually on all of your links?

Thanks!
-- Mike

**Comment by BigMcLargeHuge** [comment]
Shoot, got the wrong package, sorry :-P
